changelog:
  categories:
    - title: Highlights 🎉
      labels:
        - release-highlight
    - title: Enhancements ✨
      labels:
        - improvement
    - title: Bugs fixed 🐛️
      labels:
        - bug
    - title: Documentation improvements 📃️
      labels:
        - topic:documentation
    - title: Chores 🛠
      labels:
        - build
        - refactor
    - title: Other Changes
      labels:
        - "*"
