queue_rules:
  - name: default
    conditions:
      - "-draft"

pull_request_rules:

  - name: Label Scala Steward and Renovate PRs with 'build'
    conditions:
      - or:
        - "author=scala-steward"
        - "author=slick-scala-steward[bot]"
        - "author=renovate[bot]"
    actions:
      label:
        add:
          - build

  - name: Automatic merge on approval
    conditions:
      - "#changes-requested-reviews-by=0"
      - or:
          - "#approved-reviews-by>=1"
          - "author=nafg"
          - "author=scala-steward"
          - "author=slick-scala-steward[bot]"
          - "author=renovate[bot]"
      - and:
        - "check-success=General (8, 2.13.x)"
        - "check-success=General (17, 2.13.x)"
        - "check-success=DB2 (DB2Test, 8, 2.13.x)"
        - "check-success=DB2 (DB2Test, 17, 2.13.x)"
        - "check-success=Oracle (OracleTest, 8, 2.13.x)"
        - "check-success=Oracle (OracleTest, 17, 2.13.x)"
        - "check-success=Postgres (PostgresTest, 8, 2.13.x)"
        - "check-success=Postgres (PostgresTest, 17, 2.13.x)"
        - "check-success=SQL Server (SQLServerJTDSTest, 8, 2.13.x)"
        - "check-success=SQL Server (SQLServerJTDSTest, 17, 2.13.x)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 8, 2.13.x)"
        - "check-success=SQL Server (SQLServer2012JTDSTest, 17, 2.13.x)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 8, 2.13.x)"
        - "check-success=SQL Server (SQLServer2014JTDSTest, 17, 2.13.x)"
        - "check-success=SQL Server (SQLServer2017JTDSTest, 8, 2.13.x)"
        - "check-success=SQL Server (SQLServer2017JTDSTest, 17, 2.13.x)"
    actions:
      queue:
        name: default
        method: merge
        update_method: rebase
