queue_rules:
  - name: default
    conditions:
      - "-draft"

pull_request_rules:

  - name: Label Scala Steward and Renovate PRs with 'build'
    conditions:
      - or:
        - "author=scala-steward"
        - "author=slick-scala-steward[bot]"
        - "author=renovate[bot]"
    actions:
      label:
        add:
          - build

  - name: Automatic merge on approval
    conditions:
      - "check-success=Build and Test (11, 2.12.x)"
      - "check-success=Build and Test (11, 2.13.x)"
      - "check-success=Build and Test (17, 2.12.x)"
      - "check-success=Build and Test (17, 2.13.x)"
      - "#changes-requested-reviews-by=0"
      - or:
          - "#approved-reviews-by>=1"
          - "author=nafg"
          - "author=scala-steward"
          - "author=slick-scala-steward[bot]"
          - "author=renovate[bot]"
    actions:
      queue:
        name: default
        method: merge
        update_method: rebase
