CREATE TABLE "PERSON"(
  "ID" NUMBER(11,0) NOT NULL ENABLE,
  "PERSON_TYPE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
  "AGE" NUMBER DEFAULT 0 NOT NULL ENABLE,
  CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID")
);
CREATE TABLE "ts_default"(
	ts1 TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ts2 TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);
