drop table if exists SUPPLIERS;
drop table if exists COFFEES;
create table "SUPPLIERS" ("SUP_ID" INTEGER NOT NULL PRIMARY KEY,"SUP_NAME" VARCHAR NOT NULL,"STREET" VARCHAR NOT NULL,"CITY" VARCHAR NOT NULL,"STATE" VARCHAR NOT NULL,"ZIP" VARCHAR NOT NULL);
create table "COFFEES" ("COF_NAME" VARCHAR NOT NULL PRIMARY KEY,"SUP_ID" INTEGER NOT NULL,"PRICE" DOUBLE NOT NULL,"SALES" INTEGER NOT NULL,"TOTAL" INTEGER NOT NULL);
INSERT INTO SUPPLIERS VALUES(101, 'Acme, Inc.', '99 Market Street', 'Groundsville', 'CA', '95199');
INSERT INTO SUPPLIERS VALUES(150, 'The High Ground', '100 Coffee Lane', 'Meadows', 'CA', '93966');
INSERT INTO SUPPLIERS VALUES(49, 'Superior Coffee', '1 Party Place', 'Mendocino', 'CA', '95460');
INSERT INTO COFFEES VALUES('coffee', 1, 2.3, 4, 5);
