package slick.tracing

/**
 * Build information for the Slick tracing module.
 * This would typically be generated by sbt-buildinfo plugin.
 */
object BuildInfo {
  val version: String = "3.7.0-SNAPSHOT"
  val scalaVersion: String = "2.13.16"
  val organization: String = "com.typesafe.slick"
  val name: String = "slick-tracing"
}